create table book (book_id varchar(255) generated by default as identity, author_name varchar(255), library_id integer, no_of_copies integer, publisher varchar(255), title varchar(255), primary key (book_id))
create table borrow (borrow_id varchar(255) generated by default as identity, book_id varchar(255), no_of_book integer, user_id varchar(255), primary key (borrow_id))
create table library (library_id integer generated by default as identity, library_name varchar(255), primary key (library_id))
create table limit_table (limit_id varchar(255) not null, limit_name varchar(255), limit_value integer, primary key (limit_id))
create table user (user_id varchar(255) generated by default as identity, first_name varchar(255), last_name varchar(255), email varchar(255), primary key (user_id))

alter table limit_table add constraint UK_2m2fuuclygbvsisung03hmh3l unique (limit_name)
alter table book add constraint FKaojxagnfmppd09k35kye5eph5 foreign key (library_id) references library
alter table borrow add constraint FKgqh01ty3c1u7ja2rjdua05c36 foreign key (book_id) references book
alter table borrow add constraint FKtlx8cbafjlyp2hgfog0bdmni3 foreign key (user_id) references user